Hometask 2
dtitar/teamcity-testing-framework pull request #3
Opened 2024-01-20 13:37 UTC by dtitar

Добавлены кейсы
CreateNewProjectTest.authorizedUserShouldBeAbleCreateProjectManually()
CreateNewBuildTypeTest.userShouldBeAbleToCreateBuildTypeByUrl()
CreateNewBuildTypeTest.userShouldBeAbleToCreateBuildTypeManually()
Извиняюсь за задержку, пришлось порелоцироваться в разные страны.

Работа выполнена без учета доработок, которые рассматривали. Тк была сделана ранее. После согласования планирую внести доработки

2024-01-21 13:51 UTC, AlexPshe requested changes
Привет! 

Спасибо за выполненное ДЗ, все гуд, но нужно доделать проверку созданной сущности через API 🔥

2024-01-21 13:51 UTC, AlexPshe commented on src/main/java/com/github/dtitar/teamcity/ui/pages/ProjectPage.java
> +        Selenide.open("/project/" + projectName + "?mode=builds");
Можно использовать `format` для более элегантной параметризации строки.

2024-01-21 13:51 UTC, AlexPshe commented on src/test/java/com/github/dtitar/teamcity/ui/CreateNewBuildTypeTest.java
> +                        .getName());
Не вижу проверки созданной сущности на уровне API

2024-01-28 18:17 UTC, dtitar commented on src/main/java/com/github/dtitar/teamcity/ui/pages/ProjectPage.java
> +        Selenide.open("/project/" + projectName + "?mode=builds");
добавил format

2024-01-28 18:17 UTC, dtitar commented on src/test/java/com/github/dtitar/teamcity/ui/CreateNewBuildTypeTest.java
> +                        .getName());
не увидел это требование в дз. Добавил проверку апи

2024-02-03 09:51 UTC, dtitar commented
> Привет!
> 
> Спасибо за выполненное ДЗ, все гуд, но нужно доделать проверку созданной сущности через API 🔥

@AlexPshe подскажи, я могу мержить или надо дождаться твоего аппрува? Других комментов от тебя не видел.

2024-02-03 12:22 UTC, AlexPshe approved these changes
Теперь все ок, заапрувила!

2024-02-04 08:10 UTC, merged