Hometask 3
dtitar/teamcity-testing-framework pull request #5
Opened 2024-02-11 12:34 UTC by dtitar

Настройка пайплайна
Добавление allure
Добавление видео на упавшие тесты - не доработано до конца, тк не работал ранее с testng, все еще разбираюсь.

allure крайнего прогона: https://dtitar.github.io/teamcity-testing-framework/31/

2024-02-13 02:45 UTC, AlexPshe requested changes
Привет! 

Большое спасибо за качественное выполнение задания ⚡️

Очень круто, что получилось добавить Allure и разобраться с pages

Нужно поправить один коммент про API и будет зачтено 🔥

2024-02-13 02:45 UTC, AlexPshe commented on src/main/java/com/github/dtitar/teamcity/ui/pages/AgentsPage.java
> +        Selenide.open(AGENTS_URL);
А почему не через API?

2024-02-16 14:40 UTC, dtitar commented on src/main/java/com/github/dtitar/teamcity/ui/pages/AgentsPage.java
> +        Selenide.open(AGENTS_URL);
@AlexPshe ну, требований вроде как не было через апи. Понимаю что быстрее и стабильнее,но на тот момент времени было не много, через ui  вышло быстрее.
Переработал на апи

2024-02-16 19:01 UTC, AlexPshe approved these changes
Отлично, зачтено!

2024-02-16 19:01 UTC, AlexPshe commented on src/main/java/com/github/dtitar/teamcity/ui/pages/AgentsPage.java
> +        Selenide.open(AGENTS_URL);
Спасибо! Требования не было, но это подразумевается как само собой разумеющееся с точки зрения инженерного решения)
Чем дальше - тем меньше конкретных требований и больше отвественности на решении самого QA :)

2024-02-19 19:31 UTC, merged